name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up node using nvm
      uses: dcodeIO/setup-node-nvm@v4

    - name: Build
      run: |
        npm install
        npx webpack
